name: Docker

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  oci:
    runs-on: "ubuntu-22.04"
    name: "Build Container"
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Catch Meta Info
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/ReanSn0w/wddl
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Login to Regestry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: reansnow
          password: ${{ secrets.GHCR }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
